### ISSUE TITLE
Enhancements for startDate, stopDate, fire once, interval

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk-package-alarms#102]
This issue is an Epic to capture some enhancements for the alarms package

# Feature requests:
- Allow to specify startDate and stopDate
- Allow to specify fire once Date
- Allow to specify more granular interval 

## Allow to specify startDate and stopDate
Example configuration
```
wsk trigger create periodic \ 
--feed /whisk.system/alarms/alarm \
--param cron "*/2 * * * *" \
--param startDate “2017-10-27T14:00”
--param stopDate “2017-10-27T14:00”
```
The trigger will start to fire after startDate, and no longer fire after stopDate
The time is UTC, or user can provide time zone
- Date specified using a simplification of the ISO 8601 Extended Format. The format is as follows: YYYY-MM-DDTHH:mm:ss.sssZ more info: http://www.ecma-international.org/ecma-262/5.1/#sec-15.9.1.15

Adding this feature will allow us to deprecate and remove the parameter 'maxTriggers`
(today the default is infinite)

### Things to consider when using stopDate to clean up.
- allow user to specify entities (trigger and/or set of rules) if trigger should be deleted when the alarm is suppose to fire, but the current time is past the stopDate.

## Allow to specify fire once Date
User wants to fire a trigger only once at the specified time/date
Example configuration
```
wsk trigger create doOnce \ 
--feed /whisk.system/alarms/once \
--param date "2017-10-27T14:00"
```
## Allow to specify more granular interval
Today the cron syntax doesn't allow to specify intervals, only at the hour mark, and then repeat on the next hour. User have requests that they want more control over the internal of the fires for example every 16, or 12 minutes.
Example configuration
```
wsk trigger create interval \ 
--feed /whisk.system/alarms/interval \
--param minutes ”16" \
--param startDate “2017-10-27T14:02”
--param stopDate “2017-10-28T14:00”
```

### Future/Open
Provide in CLI and Feed Abstraction for runOnce Action
Example configuration
```
wsk invoke myaction --once --date “2017-10-28T14:00”
```
Under the hood create feed alarm Fire Once, and instead of fire trigger, we invoke the action myAction.
But we also need a way to list and identified actions to be fire in the future, maybe we create a trigger and a rule with a naming convention to allow for this management.

**Comment by daisy-ycguo** [comment]
I think this one is fixed and we can close it. @csantanapr please verify if it can be closed.

**Comment by csantanapr** [comment]
Yes @daisy-ycguo
