### ISSUE TITLE
Enhance once trigger to delete trigger and rules for user

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk-package-alarms#123]
The new trigger should accept two new optional parameters.
1. A boolean parameter to indicate to delete the trigger some time after the trigger fire
potential name for parameter: `deleteAfterFire`
this can be default to `true`
2. A an array of strings with rules to delete some time after the trigger fire
potential name for parameter: `rulesToDelete`
this parameter is invalid if `deleteAfterFire` is `false`

**Comment by rabbah** [comment]
one of these is a duplicate: https://github.com/apache/incubator-openwhisk-package-alarms/issues/86

**Comment by csantanapr** [comment]
@rabbah yep all related, good find

**Comment by csantanapr** [comment]
#86 is related but not duplicate, that talks about maxtrigger and cron. 

This one is to scope it to the new fire once trigger where there is no max trigger or stopDate. 

Will use this one to implement fireonce and collect feedback if it make sense same implementation can be applicable to the other two periodic triggers.

**Comment by csantanapr** [comment]
After some iterations, and based on the current behavior
We don't change the current behavior.
Also to eliminate ambiguity will make it one single parameter with 3 possible values

`deleteAfterFire= true | false | rules` default `false` (edited)
`true` deletes just the trigger, `false` doesn’t delete anything, `rules` delete trigger AND rules

cc @jasonpet @rabbah

**Comment by jasonpet** [comment]
fixed by PR https://github.com/apache/incubator-openwhisk-package-alarms/pull/128
