### ISSUE TITLE
log message should have trigger name on trigger not found in DB

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk-package-alarms#124]
User reported on a lifecycle DELETE for `/whisk.system/alarms/once`
He inspecting logs after the facts and see a few of these but logs don't have good info for debugging like the trigger name.

```
"2018-01-21T17:09:13.091227454Z stdout: alarm: Error invoking whisk action: 404 { error: 'could not find the trigger in the database' }"
```
This message is printed in getTrigger function which is called after verifying auth that user owns the trigger, so I think is sane to add the trigger name to the error message
https://github.com/apache/incubator-openwhisk-package-alarms/blob/master/action/lib/Database.js#L79

**Comment by jasonpet** [comment]
fixed by PR #128
