### ISSUE TITLE
[Question] How to switch active hosts?

### ISSUE THREAD

**Issue by KeonHee** [apache/incubator-openwhisk-package-alarms#133]
Currently, A provider consists of two replications, `host0` and `host1`.
and I understand that only active hosts can fire trigger.

but, I wonder how to switch active hosts when the active host is dead. 

For example, if `host0` is dead, how to transfer active status to `host1`?
Although `/active`  exists, there is no client for this.

How do you operate it?

**Comment by jasonpet** [comment]
This is done using redis publish/subscribe.  For example if active host is host0 and you run:  `publish dockermachine_alarmservice_worker0 host1` will change the active host from host0 to host1.  We simply use a monitor to ping the active endpoint and if the endpoint is not reachable the monitor will switch the active host.

**Comment by jasonpet** [comment]
You can use the active endpoint to see which host is currently active, but you can also use it to switch the active host as well if you want.  It does the redis publish/subscribe for you when pass in query params to make it the active or inactive host (eg: ?active=true).

**Comment by KeonHee** [comment]
Thank you for your answer :)
I wondered if there was a external endpoint that monitoring host.
I solved all my questions on your kind reply.
