### ISSUE TITLE
No alarm when openwhisk runs on different port

### ISSUE THREAD

**Issue by fmaschler** [apache/incubator-openwhisk-package-alarms#147]
When the openwhisk API runs on a different port than 443 it seems that periodic alarms don't work anymore. From the log you can see that the alarm action connects to the default port:
> [ERROR] [??] [alarmsTrigger] [postTrigger] there was an error invoking xxxxxxxx/guest/test_alarm {"message":"connect ECONNREFUSED 172.17.0.1:443","stack":"Error: connect ECONNREFUSED 172.17.0.1:443\n    at Object._errnoException (util.js:1022:11)\n    at _exceptionWithHostPort (util.js:1044:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)","code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"172.17.0.1","port":443}

To adjust the port on install I changed the following:
- environment variable `ROUTER_HOST` in the alarmtrigger container
- `EDGE_HOST` and `API_HOST` provided to `./installCatalog.sh`

The installation finished without errors and except from the different port openwhisk runs in default local deployment. Firing a trigger manually works but the cron jobs don't. Any ideas which configuration is missing?

**Comment by jasonpet** [comment]
looks like you found a bug.  it appears ":443" is being appended to the value of ROUTER_HOST.  I will create a PR to fix this.

**Comment by fmaschler** [comment]
As said before I adjusted the `ROUTER_HOST` variable for the alarmtrigger container. When I attach to it the variable seems correct (`172.17.0.1:4433`). Let me know if I can provide any more details.

**Comment by jasonpet** [comment]
this issue was resolved by PR #148
