### ISSUE TITLE
Why is the body of web action response base64 string, not object?

### ISSUE THREAD

**Issue by philipjkim** [apache/incubator-openwhisk-package-alarms#152]
In `action/lib/common.js` and `action/alarmWebAction.js`, there are web action responses which the body is bas64 string of JSON. I wonder why the body is base64 string, not the response or error object. 

```js
// https://github.com/apache/incubator-openwhisk-package-alarms/blob/master/action/lib/common.js#L100-L104
return {
    statusCode: statusCode,
    headers: { 'Content-Type': 'application/json' },
    body: new Buffer(JSON.stringify(params)).toString('base64')
};
```

I think the following return statement is more simple:

```js
return {
    statusCode: statusCode,
    headers: { 'Content-Type': 'application/json' },
    body: params
};
```

After testing with a simple web action, I found the difference between the base64-encoded JSON string body and object body:
- with base64 body, I get one-line JSON response like:
  ```
  {"__ow_method":"get","__ow_headers":{"host":"controllers","user-agent":"curl/7.54.0","accept":"*/*"},"__ow_path":""}
  ```
- with object body, I get multi-line pretty JSON response like:
  ```json
  {
    "__ow_method": "get",
    "__ow_headers": {
      "host": "controllers",
      "user-agent": "curl/7.54.0",
      "accept": "*/*"
    },
    "__ow_path": ""
  }
  ```

Is there any intent using base64-encoded JSON string body?

**Comment by csantanapr** [comment]
It’s just legacy in past web action only supported base64 for json output. 

I don’t see any problem removing the base64 step
