### ISSUE TITLE
Alarms package documentation refers to node-cron rather than cron

### ISSUE THREAD

**Issue by markusthoemmes** [apache/incubator-openwhisk-package-alarms#39]
@hassenius commented on [Fri Jan 27 2017](https://github.com/openwhisk/openwhisk/issues/1769)

The documentation for the alarms package refers to the format of node-cron (for example second field is optional)
https://github.com/openwhisk/openwhisk/blob/master/docs/catalog.md#firing-a-trigger-event-periodically

However, looking at the source, alarms uses the cron package:
https://github.com/openwhisk/openwhisk-package-alarms/blob/master/package.json
Which seems to require 6 fields, etc

Cron package documentation
https://www.npmjs.com/package/cron

---

@rabbah commented on [Fri Feb 24 2017](https://github.com/openwhisk/openwhisk/issues/1769#issuecomment-282426340)

@csantanapr @jasonpet move?

**Comment by jthomas** [comment]
Looks like the `cron` package supports both formats. If fields are missing from the cron string, it assumes [defaults for those missing fields values](https://github.com/kelektiv/node-cron/blob/master/lib/cron.js#L64). 

```
// If the split source string doesn't contain all digits,
// assume defaults for first n missing digits.
// This adds support for 5-digit standard cron syntax
```
https://github.com/kelektiv/node-cron/blob/master/lib/cron.js#L309-L311

Think this can be closed as not an issue?

**Comment by dgrove-oss** [comment]
Closing based on @jthomas comment from 2017.
