### ISSUE TITLE
Improve error handling on trigger fire, do not delete trigger mark it paused instead

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk-package-alarms#53]
Currently the trigger is being deleted from the DB on certain error scenarios

We need to improve how do we handle each use case, I think there are 3 use cases when firing

1. Trigger has being removed from OpenWhisk, Controller is reachable and returns Not Found (404)
2. Errors that are not recoverable (wrong auth 403, etc..), then delete trigger from db
3. Errors that with a retry can be succesfully fire on a retry, but never delete the trigger from db, and instead mark the trigger doc in db "paused: true"
4. others?
paused state for triggers is something that could be use when redudancy providers is implemented

**Comment by sjfink** [comment]
I think we need to distinguish between 'paused' feeds and 'deleted' feeds.    Feeds should support pause/resume as separate operations from create/delete

**Comment by csantanapr** [comment]
proposed design is the same for all 3 providers kafka, cloudant, alarms provided here https://github.com/openwhisk/openwhisk-package-kafka/issues/167#issuecomment-296223109
