### ISSUE TITLE
Could not get unknown property 'sourceSets' for project ':whisktests' of type org.gradle.api.Project.

### ISSUE THREAD

**Issue by Katiyman** [apache/incubator-openwhisk-package-alarms#61]
Whilw running the following command for building 
./gradlew :distDocker
 getting below error
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at docker_eaj445q4b51jflwc79mnh75jr.run(/home/nokia/openwhisk/pkg-alarm-mk/incubator-openwhisk-package-alarms/gradle/docker.gradle:43)

FAILURE: Build failed with an exception.

* Where:
Build file '/home/nokia/openwhisk/pkg-alarm-mk/incubator-openwhisk-package-alarms/tests/build.gradle' line: 28

* What went wrong:
A problem occurred evaluating project ':tests'.
> Could not get unknown property 'sourceSets' for project ':whisktests' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by jasonpet** [comment]
This error means you never set the OPENWHISK_HOME environment variable.  It should point to the location of where the openwhisk repo (https://github.com/openwhisk/openwhisk.git) was downloaded to on your computer.

**Comment by sjfink** [comment]
How about adding a check and printing an obvious error message if the variable is not set?

**Comment by jasonpet** [comment]
there already is one in the installCatalog script.  we should also add one to gradle

**Comment by Katiyman** [comment]
Thanks That resolved my issue

**Comment by zhy989** [comment]
I had set the OPENWHISK_HOME, but the error is still there.

**Comment by zhy989** [comment]
@Katiyman, How did you solve this issue?

**Comment by jasonpet** [comment]
You simply need to set OPENWHISK_HOME to the correct location to resolve the error you are getting.  What did you set it to?  It should be set to the location on your machine where you cloned https://github.com/apache/incubator-openwhisk

**Comment by zhy989** [comment]
@jasonpet 

I download the openwhisk code to /home/zhy/incubator-openwhisk

and add "OPENWHISK_HOME=/home/zhy/incubator-openwhisk" at the end of the file /etc/profile

"source /etc/porfile"

then I run "./gradlew distDocker", the error is the same as before.

**Comment by Katiyman** [comment]
@zhy989 I simply exported it as an env variable and it worked.. you can try same may be some user issue becoz of sudo

**Comment by jthomas** [comment]
I ran into this issue in the Swift runtime image.
https://github.com/apache/incubator-openwhisk-runtime-swift

One thing that confused me for a bit, I had to restart the gradle daemon (`./gradlew --stop`) before the environment variable were picked up once I updated the `.profile` file.
@zhy989

**Comment by dgrove-oss** [comment]
closing as stale
