### ISSUE TITLE
Alarm feed action should validate early if cron string is valid or not

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk-package-alarms#63]
From https://github.com/apache/incubator-openwhisk-package-alarms/blob/master/action/alarm.js#L25

The msg.cron is just taken and input is not validated

The `cron` npm package provides a way to check if pattern is valid, without starting the cron job
https://github.com/kelektiv/node-cron#how-to-check-if-a-cron-pattern-is-valid

**Comment by jasonpet** [comment]
this is complete

**Comment by csantanapr** [comment]
Sweet !
