### ISSUE TITLE
removing log message containing sensitive data

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk-package-alarms#65]
https://github.com/apache/incubator-openwhisk-package-alarms/blob/master/action/alarm.js#L4 should either be sanitized or removed completely as it logs the auth key to the activation unnecessarily; if someone is doing a demo they will inadvertently leak their key as well.

**Comment by jasonpet** [comment]
@rabbah @bjustin-ibm -This can be closed now.  I removed the entire console message containing the sensitive data as part of PR #66
