### ISSUE TITLE
Use standard output for alarm logs

### ISSUE THREAD

**Issue by daisy-ycguo** [apache/incubator-openwhisk-package-alarms#93]
The image built based on Dockerfile in the root folder is not runnable now because `/logs/alarmsTrigger_logs.log` is not exist.

Below changes are an option to fix this issue.
```
--- a/Dockerfile
+++ b/Dockerfile
@@ -16,10 +16,11 @@ RUN apt-get update --fix-missing && \
 # only package.json
 ADD package.json /alarmsTrigger/
 RUN cd /alarmsTrigger; npm install
+RUN touch ~/alarmsTrigger_logs.log

 # App
 ADD provider/. /alarmsTrigger/

 EXPOSE 8080

-CMD ["/bin/bash", "-c", "node /alarmsTrigger/app.js >> /logs/alarmsTrigger_logs.log 2>&1"]
+CMD ["/bin/bash", "-c", "node /alarmsTrigger/app.js >> ~/alarmsTrigger_logs.log 2>&1"]
```

**Comment by daisy-ycguo** [comment]
We'd better use standard output for alarm trigger logs. That's easier for operators to manage than writing to a log file, because `docker logs` and `kubectl logs` can show the standard output messages.

**Comment by jasonpet** [comment]
You simply need to create a /logs volume on your docker run command. For example: -v /var/wsklogs/alarmsTrigger:/logs
